spring.application.name=spring-ai
spring.ai.google.genai.api-key=${GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.6-flash
spring.ai.google.genai.chat.options.response-mime-type=text/plain
spring.ai.google.genai.chat.options.temperature=0.8