spring.application.name=Spring_AI

spring.ai.google.genai.api-key=${GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.6-flash
spring.ai.google.genai.chat.options.response-mime-type=text/plain
spring.ai.google.genai.chat.options.temperature=0.8

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.audio.transcription.options.model=whisper-large-v3-turbo
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.response-format=text
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.prompt=Áudio em português (Brasil) e descreve gastos financeiros \
  Contém também valor em reais, definição de estabelecimento e ações (compra, gastos...)

loggin.level.org.springframework.ai=DEBUG