spring.application.name=Spring_AI

spring.ai.google.genai.api-key=${GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.6-flash
spring.ai.google.genai.chat.options.response-mime-type=text/plain
spring.ai.google.genai.chat.options.temperature=0.8

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.audio.transcription.options.model=whisper-large-v3-turbo
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.response-format=text
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.prompt=�udio em portugu�s (Brasil) e descreve gastos financeiros \
  Cont�m tamb�m valor em reais, defini��o de estabelecimento e a��es (compra, gastos...)

spring.ai.model.audio.speech=elevenlabs
spring.ai.elevenlabs.api-key=${ELEVENLABS_API_KEY}
spring.ai.elevenlabs.tts.options.voice-id=e3yjeWnwuGsHvboTqMyB
spring.ai.elevenlabs.tts.options.output-format=mp3_22050_32

spring.jpa.show-sql=true

loggin.level.org.springframework.ai=DEBUG